n1 = input("enter a name: ")
n2 = input("enter a name: ")
n3 = input("enter a name: ")
n4 = input("enter a name: ")
n5 = input("enter a name: ")
n6 = input("enter a name: ")
n7 = input("enter a name: ")
n8 = input("enter a name: ")
n9 = input("enter a name: ")
n10 = input("enter a name: ")

x = input()

n1 = n1.title()
n2 = n2.title()
n3 = n3.title()
n4 = n4.title()
n5 = n5.title()
n6 = n6.title()
n7 = n7.title()
n8 = n8.title()
n9 = n9.title()
n10 = n10.title()

f = n10.count(x) + n9.count(x) + n8.count(x) + n7.count(x) + n6.count(x) + n5.count(x) + n4.count(x) + n3.count(x) + n2.count(x) + n1.count(x)
x = x.title()
s = n10.count(x) + n9.count(x) + n8.count(x) + n7.count(x) + n6.count(x) + n5.count(x) + n4.count(x) + n3.count(x) + n2.count(x) + n1.count(x)
f += s
print(n1, n2, n3, n4, n5, n6, n7, n8, n9, n10, "\n", f"{x} -> {f}")